name: Release workflow
on: push

jobs:
  build-job:
    name: Core Curl Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout core
        uses: actions/checkout@v2
      - name: Run script builds
        run: |
          echo Hello Vico
#          ls -las $HOME
#      - name: Checkout enterprise
#        uses: actions/checkout@v1
#        with:
#          fetch-depth: 1
#          repository: https://github.com/dotCMS/core.git
#          ref: release-5.2.2
#          token: ${{ secrets.GITHUB_ENTERPRISE_TOKEN }}
