name: Release workflow
on: push

jobs:
  build-job:
    name: Core Curl Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout core
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: test-base-image-build
        run: |
          export CURRENT_BRANCH=$(basename $GITHUB_REF)
          docker build -t gcr.io/$PROJECT_ID/integration-tests-image:$GITHUB_RUN_NUMBER \
            --build-arg BUILD_FROM=COMMIT \
            --build-arg BUILD_ID=$CURRENT_BRANCH \
            --build-arg BUILD_HASH=$COMMIT_SHA \
            --build-arg LICENSE_KEY=123 \
            ./docker/tests/integration/
        env:
          PROJECT_ID: cicd-246518
      - name: curl-test-image-build
        run: |
          export CURRENT_BRANCH=$(basename $GITHUB_REF)
          docker build -t gcr.io/$PROJECT_ID/curl-tests-image:$GITHUB_RUN_NUMBER \
            --build-arg BUILD_FROM=COMMIT \
            --build-arg BUILD_ID=$CURRENT_BRANCH \
            --build-arg BUILD_HASH=$COMMIT_SHA \
            --build-arg LICENSE_KEY=123 \
            --build-arg FROM_IMAGE=gcr.io/$PROJECT_ID/integration-tests-image:$GITHUB_RUN_NUMBER \
            ./docker/tests/curl/
        env:
          PROJECT_ID: cicd-246518
      - name: sidecar-image-build
        run: |
          export CURRENT_BRANCH=$(basename $GITHUB_REF)
          docker build -t gcr.io/$PROJECT_ID/dotcms-sidecar-image:$GITHUB_RUN_NUMBER \
            --build-arg BUILD_FROM=COMMIT \
            --build-arg BUILD_ID=$CURRENT_BRANCH \
            --build-arg BUILD_HASH=$COMMIT_SHA \
            ./docker/tests/sidecar/
        env:
          PROJECT_ID: cicd-246518
#      - name: Checkout enterprise
#        uses: actions/checkout@v1
#        with:
#          fetch-depth: 1
#          repository: https://github.com/dotCMS/core.git
#          ref: release-5.2.2
#          token: ${{ secrets.GITHUB_ENTERPRISE_TOKEN }}
